name: Build ROGueENEMY

on:
  push:
    branches: [ main ]
    tags: '*'
  workflow_dispatch:

env:
  PKGDEST: "/tmp/pkg"
  BUILDDIR: "/tmp/build"

jobs:
  build-pkg:
    runs-on: ubuntu-latest
    outputs:
      full_version: ${{ steps.set-pkg-version.outputs.full_version }}

    container: archlinux:base-devel

    steps:
      - uses: actions/checkout@v3
      - name: Create build user
        run: |
          useradd -m build
          mkdir /home/build/pkg
          cp -v * /home/build/pkg/
          chown -vR build /home/build/pkg
          rm /home/build/pkg/README.md
      - name: Set up pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          mkdir -p /etc/gnupg && echo "auto-key-retrieve" >> /etc/gnupg/gpg.conf
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf
      - name: Set up git
        run: |
          pacman -Syu --noconfirm git libevdev clang llvm lld rsync
      - name: Generate .SRCINFO
        run: |
          su build bash -c "cd /home/build/pkg && makepkg --printsrcinfo > /home/build/pkg/.SRCINFO"
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm $(sed -n -e 's/^[[:space:]]*\(make\)\?depends\(_x86_64\)\? = \([[:alnum:][:punct:]]*\)[[:space:]]*$/\3/p' /home/build/pkg/.SRCINFO)
      - name: Customize makepkg.conf
        run: |
          sed -i -e 's/BUILDENV=(!distcc color !ccache check !sign)/BUILDENV=(!distcc color !ccache !check !sign)/g' /etc/makepkg.conf
          sed -i -e 's/-march=x86-64 -mtune=generic/-march=znver4/g' /etc/makepkg.conf
          sed -i -e 's/-O2/-O3/g' /etc/makepkg.conf
          sed -i -e 's/!lto/lto/g' /etc/makepkg.conf
      - name: Build Package
        id: build-package
        shell: bash
        run: |
          su build bash -c "cd /home/build/pkg  && LTOFLAGS='flto=full' LD=lld CC=clang CXX=clang MAKEFLAGS=-j$(nproc) makepkg"
      - name: Set package version
        id: set-pkg-version
        shell: bash
        run: |
          . /home/build/pkg/PKGBUILD
          full_version=${pkgver}-${pkgrel}
          echo "full_version=$full_version" >> "$GITHUB_OUTPUT"
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: pkg-upload
          path: |
            ${{ env.PKGDEST }}/*.pkg.tar.zst
          if-no-files-found: error

  make-release:
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    needs: [build-pkg]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: pkg-upload
          path: ${{ env.PKGDEST }}
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: pkg-release-${{needs.build-pkg.outputs.full_version}}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            ${{ env.PKGDEST }}/*.pkg.tar.zst